const String INVOICE_MERCHANT = "merchant_invoice";
const String INVOICE_SPARE = "spare";
const String INVOICE_MAINTENANCE = "maintenance";
const String INVOICE_RETURN = "return_invoice";
const String INVOICE_MERCHANT_RETURN = "merchant_return";

const String EMAIL_POSTFIX = "@firebase.com";

const String MAIN_TYPE_FAULT = "صيانه اعطال";
const String MAIN_TYPE_PERIODIC = "صيانة دورية";
// const String MAIN_TYPE_RETURN

const Map<String, String> colorNameToHex = {
  "أسود": "0xFF000000",
  "أبيض": "0xFFFFFFFF",
  "أحمر": "0xFFFF0000",
  "أزرق": "0xFF0000FF",
  "أخضر": "0xFF00FF00",
  "أصفر": "0xFFFFFF00",
  "رمادي": "0xFF808080",
  "فضي": "0xFFC0C0C0",
  "برتقالي": "0xFFFFA500",
  "بني": "0xFFA52A2A",
  "بيج": "0xFFF5F5DC",
  "ذهبي": "0xFFFFD700",
  "أرجواني": "0xFF800080",
  "وردي": "0xFFFFC0CB",
  "ماروني": "0xFF800000",
  "كحلي": "0xFF000080",
  "أخضر مزرق": "0xFF008080",
  "فيروزي": "0xFF40E0D0",
  "ليموني": "0xFF00FF00",
  "زيتوني": "0xFF808000",
  "فوشي": "0xFFFF00FF",
  "سماوي": "0xFF00FFFF",
  "عاجي": "0xFFFFFFF0",
  "مرجاني": "0xFFFF7F50",
  "مائي": "0xFF00FFFF",
  "شكولاتة": "0xFFD2691E",
  "كاكي": "0xFFF0E68C",
  "لافندر": "0xFFE6E6FA",
  "أوركيدي": "0xFFDA70D6",
  "خوخي": "0xFFDDA0DD",
  "سلموني": "0xFFFA8072",
  "سييني": "0xFFA0522D",
  "أسمر": "0xFFD2B48C",
  "قمحي": "0xFFF5DEB3",
};

const Map<String, List<String>> carMakesAndModels = {
  'Toyota': [
    'Camry',
    'Corolla',
    'Prius',
    'RAV4',
    'Highlander',
    'Tacoma',
    'Tundra',
    'Avalon',
    '4Runner',
    'Sienna',
    'Yaris',
    'Hilux',
    'Fortuner'
  ],
  'Honda': [
    'Civic',
    'Accord',
    'CR-V',
    'Pilot',
    'Fit',
    'Odyssey',
    'Ridgeline',
    'HR-V',
    'Insight',
    'Passport',
    'City',
    'Jazz'
  ],
  'Ford': [
    'F-150',
    'Mustang',
    'Explorer',
    'Focus',
    'Escape',
    'Fusion',
    'Edge',
    'Expedition',
    'Ranger',
    'Bronco'
  ],
  'Chevrolet': [
    'Silverado',
    'Malibu',
    'Equinox',
    'Impala',
    'Tahoe',
    'Suburban',
    'Camaro',
    'Blazer',
    'Colorado',
    'Traverse',
    'Aveo',
    'Optra',
    'Cruze',
    'Spark',
    'Lanos'
  ],
  'Nissan': [
    'Altima',
    'Sentra',
    'Maxima',
    'Rogue',
    'Murano',
    'Pathfinder',
    'Frontier',
    'Titan',
    'Armada',
    'Versa',
    'Sunny',
    'Qashqai',
    'Juke',
    'Patrol'
  ],
  'BMW': [
    '3 Series',
    '5 Series',
    '7 Series',
    'X3',
    'X5',
    'X1',
    'X6',
    'Z4',
    'i3',
    'i8'
  ],
  'Mercedes-Benz': [
    'C-Class',
    'E-Class',
    'S-Class',
    'GLC',
    'GLE',
    'GLA',
    'GLS',
    'A-Class',
    'B-Class',
    'G-Class'
  ],
  'Volkswagen': [
    'Golf',
    'Passat',
    'Jetta',
    'Tiguan',
    'Atlas',
    'Beetle',
    'Arteon',
    'Touareg',
    'ID.4',
    'Polo'
  ],
  'Audi': ['A3', 'A4', 'A6', 'Q3', 'Q5', 'Q7', 'Q8', 'A5', 'A7', 'TT'],
  'Hyundai': [
    'Elantra',
    'Sonata',
    'Tucson',
    'Santa Fe',
    'Kona',
    'Palisade',
    'Accent',
    'Veloster',
    'Ioniq',
    'Venue'
  ],
  'Kia': [
    'Optima',
    'Sorento',
    'Sportage',
    'Soul',
    'Stinger',
    'Telluride',
    'Seltos',
    'Rio',
    'Forte',
    'Niro',
    'Cerato',
    'Picanto'
  ],
  'Subaru': [
    'Impreza',
    'Outback',
    'Forester',
    'Legacy',
    'Crosstrek',
    'Ascent',
    'WRX',
    'BRZ',
    'Tribeca',
    'XV'
  ],
  'Mazda': [
    'Mazda3',
    'Mazda6',
    'CX-5',
    'CX-9',
    'MX-5 Miata',
    'CX-3',
    'CX-30',
    'RX-8',
    'Mazda2',
    'CX-7'
  ],
  'Lexus': ['IS', 'ES', 'GS', 'RX', 'NX', 'LX', 'GX', 'UX', 'LS', 'RC'],
  'Jeep': [
    'Wrangler',
    'Grand Cherokee',
    'Cherokee',
    'Compass',
    'Renegade',
    'Gladiator',
    'Patriot',
    'Liberty',
    'Commander',
    'Wagoneer'
  ],
  'Dodge': [
    'Charger',
    'Challenger',
    'Durango',
    'Journey',
    'Grand Caravan',
    'Viper',
    'Dart',
    'Avenger',
    'Magnum',
    'Nitro'
  ],
  'Tesla': [
    'Model S',
    'Model 3',
    'Model X',
    'Model Y',
    'Cybertruck',
    'Roadster'
  ],
  'Cadillac': [
    'CTS',
    'XT5',
    'Escalade',
    'ATS',
    'XT4',
    'XT6',
    'CT6',
    'SRX',
    'XLR',
    'DTS'
  ],
  'Porsche': [
    '911',
    'Cayenne',
    'Panamera',
    'Macan',
    'Boxster',
    'Taycan',
    'Cayman',
    '918 Spyder',
    'Carrera GT',
    '968'
  ],
  'Jaguar': [
    'XE',
    'XF',
    'XJ',
    'F-Pace',
    'E-Pace',
    'I-Pace',
    'F-Type',
    'XK',
    'X-Type',
    'S-Type'
  ],
  'Land Rover': [
    'Range Rover',
    'Discovery',
    'Evoque',
    'Defender',
    'Velar',
    'Freelander',
    'Sport',
    'Discovery Sport',
    'LR4',
    'LR2'
  ],
  'Volvo': [
    'S60',
    'S90',
    'XC40',
    'XC60',
    'XC90',
    'V60',
    'V90',
    'C30',
    'C70',
    'S40'
  ],
  'Mini': [
    'Cooper',
    'Clubman',
    'Countryman',
    'Convertible',
    'Paceman',
    'Coupe',
    'Roadster',
    'Clubvan'
  ],
  'Mitsubishi': [
    'Lancer',
    'Outlander',
    'Eclipse Cross',
    'Mirage',
    'Pajero',
    'ASX',
    'Montero',
    'Galant',
    '3000GT',
    'Endeavor',
    'Attrage'
  ],
  'Ferrari': [
    '488',
    'F8',
    '812',
    'Portofino',
    'Roma',
    'SF90',
    'LaFerrari',
    'California',
    '458',
    'Enzo'
  ],
  'Lamborghini': [
    'Huracan',
    'Aventador',
    'Urus',
    'Gallardo',
    'Murcielago',
    'Countach',
    'Diablo',
    'Sian',
    'Reventon',
    'Centenario'
  ],
  'Bentley': [
    'Continental',
    'Flying Spur',
    'Bentayga',
    'Mulsanne',
    'Arnage',
    'Azure',
    'Brooklands',
    'Turbo R'
  ],
  'Rolls-Royce': [
    'Phantom',
    'Ghost',
    'Wraith',
    'Dawn',
    'Cullinan',
    'Silver Shadow',
    'Silver Spirit',
    'Silver Seraph',
    'Corniche',
    'Camargue'
  ],
  'Maserati': [
    'Ghibli',
    'Levante',
    'Quattroporte',
    'GranTurismo',
    'GranCabrio',
    'MC12',
    'Bora',
    'Indy',
    'Biturbo',
    'Shamal'
  ],
  'Aston Martin': [
    'DB11',
    'Vantage',
    'DBS',
    'Rapide',
    'Vanquish',
    'DB9',
    'DB7',
    'One-77',
    'Lagonda',
    'Virage'
  ],
  'Acura': [
    'ILX',
    'TLX',
    'RLX',
    'RDX',
    'MDX',
    'NSX',
    'ZDX',
    'TSX',
    'RSX',
    'CL'
  ],
  'Infiniti': [
    'Q50',
    'Q60',
    'QX50',
    'QX60',
    'QX80',
    'G37',
    'FX35',
    'EX35',
    'M37',
    'QX70'
  ],
  'Lincoln': [
    'MKZ',
    'Nautilus',
    'Aviator',
    'Navigator',
    'Corsair',
    'MKX',
    'MKT',
    'Continental',
    'Town Car',
    'LS'
  ],
  'Buick': [
    'Encore',
    'Enclave',
    'Regal',
    'LaCrosse',
    'Envision',
    'Verano',
    'Cascada',
    'Park Avenue',
    'Riviera',
    'LeSabre'
  ],
  'Chrysler': [
    '300',
    'Pacifica',
    'Voyager',
    'Aspen',
    'Crossfire',
    'PT Cruiser',
    'Sebring',
    '200',
    'Town & Country',
    'Imperial'
  ],
  'Fiat': [
    '500',
    '500X',
    '124 Spider',
    'Panda',
    'Tipo',
    'Punto',
    'Bravo',
    'Doblo',
    'Multipla',
    'Stilo',
    'Linea'
  ],
  'Alfa Romeo': [
    'Giulia',
    'Stelvio',
    '4C',
    'Giulietta',
    'MiTo',
    'Spider',
    'GTV',
    'Brera',
    '8C',
    '159'
  ],
  'Genesis': ['G70', 'G80', 'G90', 'GV70', 'GV80'],
  'Suzuki': [
    'Swift',
    'Vitara',
    'Baleno',
    'Ignis',
    'Ciaz',
    'Alto',
    'Jimny',
    'S-Cross',
    'Kizashi',
    'Ertiga'
  ],
  'Peugeot': [
    '208',
    '308',
    '3008',
    '5008',
    '508',
    '2008',
    '4008',
    '106',
    '206',
    '301',
    '206',
    '306'
  ],
  'Renault': [
    'Clio',
    'Megane',
    'Captur',
    'Kadjar',
    'Scenic',
    'Talisman',
    'Zoe',
    'Koleos',
    'Fluence',
    'Espace',
    'Logan',
    'Sandero',
    'Duster'
  ],
  'Citroën': [
    'C3',
    'C4',
    'C5 Aircross',
    'Berlingo',
    'Dispatch',
    'C1',
    'C2',
    'C5',
    'DS3',
    'DS4'
  ],
  'Seat': [
    'Ibiza',
    'Leon',
    'Ateca',
    'Arona',
    'Tarraco',
    'Alhambra',
    'Toledo',
    'Altea',
    'Mii',
    'Cordoba'
  ],
  'Skoda': [
    'Fabia',
    'Octavia',
    'Superb',
    'Kodiaq',
    'Kamiq',
    'Karoq',
    'Scala',
    'Rapid',
    'Citigo',
    'Yeti'
  ],
  'Saab': ['9-3', '9-5', '900', '9000', 'Sonett', '9-2X', '9-7X'],
  'Isuzu': [
    'D-Max',
    'Mu-X',
    'Trooper',
    'Rodeo',
    'Axiom',
    'Amigo',
    'VehiCROSS',
    'Ascender',
    'i-Series'
  ],
  'Hummer': ['H1', 'H2', 'H3'],
  'Scion': ['tC', 'xB', 'FR-S', 'iM', 'iA', 'xD'],
  'Smart': ['Fortwo', 'Forfour'],
  'Opel': [
    'Astra',
    'Corsa',
    'Insignia',
    'Mokka',
    'Zafira',
    'Meriva',
    'Vectra',
    'Adam',
    'Karl',
    'Grandland X'
  ],
  'Holden': [
    'Commodore',
    'Cruze',
    'Colorado',
    'Astra',
    'Captiva',
    'Barina',
    'Monaro',
    'Ute',
    'Trax',
    'Maloo'
  ],
  'SsangYong': [
    'Tivoli',
    'Rexton',
    'Korando',
    'Musso',
    'Actyon',
    'Kyron',
    'Rodius',
    'XLV'
  ],
  'Tata': [
    'Nexon',
    'Harrier',
    'Safari',
    'Tiago',
    'Altroz',
    'Hexa',
    'Tigor',
    'Nano',
    'Zest',
    'Bolt'
  ],
  'Mahindra': [
    'XUV500',
    'Scorpio',
    'Thar',
    'Bolero',
    'Marazzo',
    'KUV100',
    'XUV300',
    'TUV300',
    'Verito',
    'Quanto'
  ],
  'Daihatsu': [
    'Terios',
    'Sirion',
    'Copen',
    'Charade',
    'Mira',
    'Rocky',
    'Ayla',
    'Tanto',
    'Luxio',
    'Gran Max'
  ],
  'Chery': ['Tiggo', 'Arrizo', 'Envy', 'Elara', 'Fulwin'],
  'Geely': ['Emgrand 7', 'X7', 'Panda', 'GX3', 'LC Cross'],
  'MG': ['ZS', 'RX5', '5', '6', 'HS']
};
